- replace:
    path: "/etc/hadoop/mapred-site.xml"
    regexp: "^<configuration>\n<property>\n<name>mapred.job.tracker</name>\n<value>{{job_tracker_ip}}:9002</value>\n</property>"
    replace: "<configuration>"
- replace:
    path: "/etc/hadoop/mapred-site.xml"
    regexp: "^<configuration>"
    replace: "<configuration>\n<property>\n<name>mapred.job.tracker</name>\n<value>{{job_tracker_ip}}:9002</value>\n</property>"
- replace:
    path: "/etc/hadoop/core-site.xml"
    regexp: "^<configuration>\n<property>\n<name>fs.default.name</name>\n<value>hdfs://{{name_node_ip}}:9001</value>\n</property>"
    replace: "<configuration>"
- replace:
    path: "/etc/hadoop/core-site.xml"
    regexp: "^<configuration>"
    replace: "<configuration>\n<property>\n<name>fs.default.name</name>\n<value>hdfs://{{name_node_ip}}:9001</value>\n</property>"
- command: "hadoop-daemon.sh start jobtracker "
