- template: 
    src: "mapred.xml.j2"
    dest: "/etc/hadoop/mapred-site.xml"
- template: 
    src: "name_node_core.xml.j2"
    dest: "/etc/hadoop/core-site.xml"
- command: hadoop-daemon.sh stop jobtracker
  ignore_errors: yes
- command: hadoop-daemon.sh start jobtracker

