- copy: 
    src: /media/sf_share/Software/jdk-8u171-linux-x64.rpm
    dest: jdk-8u171-linux-x64.rpm 
- package:
     name: jdk-8u171-linux-x64.rpm
     state: present
- copy:  
    src: /media/sf_share/Software/hadoop-1.2.1-1.x86_64.rpm
    dest: hadoop-1.2.1-1.x86_64.rpm
- command: rpm -ivh hadoop-1.2.1-1.x86_64.rpm --force
- lineinfile:
    path: /root/.bashrc
    line: export PATH=/usr/java/jdk1.8.0_171-amd64/bin/:$PATH 
- lineinfile:
    path: /root/.bashrc
    line: export JAVA_HOME=/usr/java/jdk1.8.0_171-amd64/  

