- name: "docker Install"
  package: 
    name: docker-ce
    state: present
- name: "start service"
  service:
    name: docker
    state: started
- name: "copy pip "
  copy:
     src: /media/sf_share/get-pip.py
     dest: get-pip.py
- name: "install pip"
  command: "python get-pip.py"
- name: "install docker"
  pip:
     name: docker-py
     state: present
